#!/usr/bin/env Rscript
f <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])
if (!file.exists(f)) f <- gsub("~+~", " ", f, fixed = TRUE)
root <- dirname(normalizePath(f, mustWork = TRUE))
source(file.path(root, "real_data_paths.R"))
source(file.path(root, "ADNI_parallel.R"))
paths <- application_paths(root)
cat("R:", as.character(getRversion()), "| architecture:", R.version$arch, "| OS:", Sys.info()[["sysname"]], "\n")
adni_print_core_plan(adni_core_plan(as.numeric(Sys.getenv("EIVGP_CORES", "4"))))
packages <- c("eivGP", "knitr", "ggplot2", "patchwork", "jsonlite", "posterior", "kergp", "LVGP", "EzGP")
versions <- vapply(packages, function(p) if (requireNamespace(p, quietly = TRUE))
  as.character(utils::packageVersion(p)) else "MISSING", character(1))
print(data.frame(package = packages, version = versions), row.names = FALSE)
print(paths)
if (any(versions == "MISSING") || versions["eivGP"] != "0.3.1") stop("Run: Rscript codes/applications/setup_real_data.R")
source(file.path(root, "check_prepared_data.R"))
check_prepared_data(root)
cat("No fitting started.\n")
