structure(list(schema_version = "2.0.0", study = "study2", mode = "smoke", 
    run_id = "study2-smoke-v2", code_dir = "/Library/Frameworks/R.framework/Versions/4.6/Resources/library/eivGP/simulation-source", 
    output_root = "/Users/sheng/Documents/GitHub/eivGP/artifacts/simulation-runs/study2", 
    data_root = "/Users/sheng/Documents/GitHub/eivGP/artifacts/data-synthetic/smoke-v2/study2", 
    stages = c("fit", "aggregate"), cells = list(list(id = "primary_q2", 
        role = "primary_proxy_dimension", scenario = "primary", 
        q = 2L, d = 2L, m = 4L, n = 120L, n_test = 60L, n_rep = 1L, 
        calibration_grid = 6L, run_ablations = TRUE, evaluate_f = FALSE, 
        evaluate_u = TRUE), list(id = "primary_q3", role = "primary_proxy_dimension", 
        scenario = "primary", q = 3L, d = 2L, m = 4L, n = 120L, 
        n_test = 60L, n_rep = 1L, calibration_grid = 6L, run_ablations = TRUE, 
        evaluate_f = FALSE, evaluate_u = TRUE), list(id = "primary_q4_calibration", 
        role = "primary_calibration_curve", scenario = "primary", 
        q = 4L, d = 2L, m = 4L, n = 120L, n_test = 60L, n_rep = 1L, 
        calibration_grid = c(0L, 6L), run_ablations = TRUE, evaluate_f = TRUE, 
        evaluate_u = TRUE), list(id = "additive_q4", role = "negative_control", 
        scenario = "latent_additive_control", q = 4L, d = 2L, 
        m = 4L, n = 120L, n_test = 60L, n_rep = 1L, calibration_grid = 6L, 
        run_ablations = TRUE, evaluate_f = FALSE, evaluate_u = FALSE), 
        list(id = "high_uncertainty_q4", role = "uncertainty_control", 
            scenario = "high_uncertainty", q = 4L, d = 2L, m = 4L, 
            n = 120L, n_test = 60L, n_rep = 1L, calibration_grid = 6L, 
            run_ablations = TRUE, evaluate_f = FALSE, evaluate_u = FALSE), 
        list(id = "logistic_q4", role = "appendix_misspecification", 
            scenario = "logistic_misspec", q = 4L, d = 2L, m = 4L, 
            n = 120L, n_test = 60L, n_rep = 1L, calibration_grid = 6L, 
            run_ablations = FALSE, evaluate_f = FALSE, evaluate_u = FALSE), 
        list(id = "primary_q6", role = "appendix_sparse_pattern_stress", 
            scenario = "primary", q = 6L, d = 2L, m = 4L, n = 120L, 
            n_test = 80L, n_rep = 1L, calibration_grid = 6L, 
            run_ablations = TRUE, evaluate_f = FALSE, evaluate_u = TRUE)), 
    published_methods = c("UC-GP", "LVGP", "EzGP"), strict_competitors = FALSE, 
    fail_closed = FALSE, use_cache = TRUE, parallel = list(level = "replications", 
        workers = 4L), predictive_latent_sampler = "minimax_tilting", 
    mcmc = list(n_iter = 120L, burn = 40L, thin = 2L, n_chains = 1L, 
        rhat_limit = 1.05, raw_ess_limit = 20L, target_bulk_ess_limit = 10L, 
        target_tail_ess_limit = 10L, require_gate = FALSE), measurement_mcmc = list(
        n_iter = 120L, burn = 40L, thin = 2L, n_chains = 2L), 
    evaluation = list(n_pred_draw = 30L, n_m_eval = 8L, n_m_draw = 12L, 
        n_m_latent = 16L, n_m_truth = 100L, n_oracle_pool = 5000L), 
    ablation_gp = list(n_starts = 3L, maxit = 200L), created_at = "2026-09-02 13:02:37 UTC"), class = c("mixedgp_simulation_config", 
"list"))
