#!/usr/bin/env Rscript
f <- grep("^--file=", commandArgs(FALSE), value = TRUE)
root <- dirname(normalizePath(sub("^--file=", "", f[1])))
cat("R:", as.character(getRversion()), "| architecture:", R.version$arch,
    "| OS:", Sys.info()[["sysname"]], "\n")
cat("Total core budget:", Sys.getenv("EIVGP_CORES", "not specified"), "\n")
source(file.path(root, "ADNI-toledo", "adni_parallel.R"))
repeat_spec <- Sys.getenv("ADNI_REPEATS", Sys.getenv("ADNI_REPEAT_ID", "2"))
if (!repeat_spec %in% c("2", "3", "2,3", "3,2")) stop("Invalid ADNI_REPEATS")
n_repeats <- length(strsplit(repeat_spec, ",", fixed = TRUE)[[1]])
plan <- adni_core_plan(as.integer(Sys.getenv("EIVGP_CORES", Sys.getenv("EIVGP_N_CORES", "4"))),
  n_folds = 3L * n_repeats, max_fold_workers = as.integer(Sys.getenv("ADNI_MAX_FOLD_WORKERS", "6")))
adni_print_core_plan(plan)
packages <- c("eivGP", "knitr", "ggplot2", "patchwork", "jsonlite", "posterior", "kergp", "LVGP", "EzGP")
present <- vapply(packages, requireNamespace, logical(1), quietly = TRUE)
versions <- vapply(packages, function(p) if (requireNamespace(p, quietly = TRUE))
  as.character(utils::packageVersion(p)) else "MISSING", character(1))
print(data.frame(package = packages, version = versions), row.names = FALSE)
cat("ADNI input:", Sys.getenv("ADNI_DATA_DIR"), "\n")
cat("ADNI output:", Sys.getenv("ADNI_OUTPUT_DIR"), "\n")
cat("Ocean input:", Sys.getenv("OCEAN_DATA_DIR"), "\n")
cat("Ocean output:", Sys.getenv("OCEAN_OUTPUT_DIR"), "\n")
if (!all(present) || versions["eivGP"] != "0.3.1")
  stop("Dependencies are not ready. Run: bash codes/real-data/run_mac.sh setup")
code <- tempfile(fileext = ".R")
invisible(knitr::purl(file.path(root, "Raw_Data_Processing.Rmd"), output = code, quiet = TRUE))
env <- new.env(parent = globalenv()); env$DATA_WORKFLOW_DIR <- root
tryCatch(sys.source(code, envir = env), finally = unlink(code))
adni_dir <- Sys.getenv("ADNI_DATA_DIR", file.path(root, "ADNI-toledo", "data"))
adni_ready <- all(file.exists(file.path(adni_dir, c("toledo_adni_cohort_n495.csv",
  "toledo_adni_balanced_repeated_3fold.csv"))))
cat("ADNI readiness:", if (adni_ready) "data checks passed; ready for smoke test" else "data unavailable", "\n")
cat("No fitting was started. Ocean availability is reported separately above.\n")
if (!adni_ready) quit(status = 1L)
